package sk.upjs.ics.kopr.projekt1.klient;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JProgressBar;

public class OknoKlienta extends javax.swing.JFrame {

    private Klient klient;
    private InfoNaPokracovanie infoNaPokracovanie;

    private ProgresBarWorker progresBarWorker;
    private KopirovaciWorker kopirovaciWorker;

    public OknoKlienta() {
        initComponents();

        File info = new File("infooprerusenom.txt");
        if (info.exists()) { // je mozne pokracovat v stahovani suboru
            Scanner citac = null;
            try {
                citac = new Scanner(info);
                String nazov = citac.next();
                int pocetSoketov = citac.nextInt();
                long pocetPrijatychBajtov = citac.nextLong();
                List<Long> offsety = new ArrayList<>();
                for (int i = 0; i < pocetSoketov; i++) {
                    offsety.add(citac.nextLong());
                }

                infoNaPokracovanie = new InfoNaPokracovanie(nazov, pocetSoketov, pocetPrijatychBajtov, offsety);

                lblPrerusenyNazov.setText(nazov);
                lblPrerusenyNazov.setEnabled(true);
                btnObnovit.setEnabled(true);

            } catch (FileNotFoundException ex) {
                System.err.println("Nepodarilo sa otvorit subor s informaciami o pokracovani.");
            } finally {
                if (citac != null) {
                    // po precitani subor vymazeme
                    citac.close();
                    info.delete();
                }
            }
        }
    }

    private void spustiProgresBarWorker() {
        progresBarWorker = new ProgresBarWorker(this, klient);
        progresBarWorker.execute();
    }

    private void spustiKopirovaciWorker() {
        kopirovaciWorker = new KopirovaciWorker(this, klient);
        kopirovaciWorker.execute();
    }

    public void zastavProgresBarWorker() {
        progresBarWorker.cancel(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNoveNazov = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPocetSoketov = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPrerusenyNazov = new javax.swing.JLabel();
        btnZacat = new javax.swing.JButton();
        btnObnovit = new javax.swing.JButton();
        progresBar = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        btnPrerusit = new javax.swing.JButton();
        btnUkoncit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblPercento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("KOPR kopírovač");

        jLabel2.setText("Názov súboru:");

        jLabel3.setText("Počet soketov:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Začať nové kopírovanie");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Obnoviť prerušené kopírovanie");

        jLabel6.setText("Názov súboru:");

        lblPrerusenyNazov.setText("nie je k dispozícii");
        lblPrerusenyNazov.setEnabled(false);

        btnZacat.setText("Začať");
        btnZacat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZacatActionPerformed(evt);
            }
        });

        btnObnovit.setText("Obnoviť");
        btnObnovit.setEnabled(false);
        btnObnovit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObnovitActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Priebeh kopírovania");

        btnPrerusit.setText("Prerušiť");
        btnPrerusit.setEnabled(false);
        btnPrerusit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrerusitActionPerformed(evt);
            }
        });

        btnUkoncit.setText("Ukončiť");
        btnUkoncit.setEnabled(false);
        btnUkoncit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkoncitActionPerformed(evt);
            }
        });

        lblPercento.setText("0 %");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addComponent(progresBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPrerusit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnUkoncit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblPercento))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(30, 30, 30)
                                .addComponent(lblPrerusenyNazov)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnObnovit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPocetSoketov, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNoveNazov, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnZacat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNoveNazov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPocetSoketov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnZacat)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblPrerusenyNazov)
                    .addComponent(btnObnovit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progresBar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUkoncit)
                            .addComponent(btnPrerusit)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPercento)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZacatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZacatActionPerformed
        String nazovSuboru = txtNoveNazov.getText();
        String pocetSoketovTxt = txtPocetSoketov.getText();

        if (nazovSuboru.isEmpty() || pocetSoketovTxt.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Nesprávne vyplnené polia!",
                    "Chyba",
                    ERROR_MESSAGE);
            return;
        }

        File subor = new File(nazovSuboru);
        if (subor.exists()) {
            JOptionPane.showMessageDialog(this,
                    "Súbor s daným názvom už existuje.",
                    "Chyba",
                    ERROR_MESSAGE);
            return;
        }

        int pocetSoketov = Integer.parseInt(pocetSoketovTxt);

        klient = new Klient(nazovSuboru, pocetSoketov);

        spustiKopirovaciWorker();
        spustiProgresBarWorker();
        
        btnZacat.setEnabled(false);
        btnObnovit.setEnabled(false);
        btnPrerusit.setEnabled(true);
        btnUkoncit.setEnabled(true);
    }//GEN-LAST:event_btnZacatActionPerformed

    private void btnPrerusitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrerusitActionPerformed
        klient.prerusStahovanie(true);
        JOptionPane.showMessageDialog(this,
                "Sťahovanie bolo prerušené. Program sa ukončí.",
                "Info",
                INFORMATION_MESSAGE);
        while (!kopirovaciWorker.isDone()) {
            // cakame, kym worker urobi operacie po skonceni kopirovania
            continue;
        }
        System.exit(0);
    }//GEN-LAST:event_btnPrerusitActionPerformed

    private void btnUkoncitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkoncitActionPerformed
        klient.prerusStahovanie(false);
        JOptionPane.showMessageDialog(this,
                "Sťahovanie bolo ukončené. Program sa ukončí.",
                "Info",
                INFORMATION_MESSAGE);
        while (!kopirovaciWorker.isDone()) {
            // cakame, kym worker urobi operacie po skonceni kopirovania
            continue;
        }
        System.exit(0);
    }//GEN-LAST:event_btnUkoncitActionPerformed

    private void btnObnovitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObnovitActionPerformed
        klient = new Klient(infoNaPokracovanie);
        
        spustiKopirovaciWorker();
        spustiProgresBarWorker();

        btnZacat.setEnabled(false);
        btnObnovit.setEnabled(false);
        btnPrerusit.setEnabled(true);
        btnUkoncit.setEnabled(true);     
    }//GEN-LAST:event_btnObnovitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoKlienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoKlienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoKlienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoKlienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoKlienta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObnovit;
    private javax.swing.JButton btnPrerusit;
    private javax.swing.JButton btnUkoncit;
    private javax.swing.JButton btnZacat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblPercento;
    private javax.swing.JLabel lblPrerusenyNazov;
    private javax.swing.JProgressBar progresBar;
    private javax.swing.JTextField txtNoveNazov;
    private javax.swing.JTextField txtPocetSoketov;
    // End of variables declaration//GEN-END:variables

    public JProgressBar getProgresBar() {
        return progresBar;
    }

    public JButton getBtnObnovit() {
        return btnObnovit;
    }

    public JButton getBtnPrerusit() {
        return btnPrerusit;
    }

    public JButton getBtnUkoncit() {
        return btnUkoncit;
    }

    public JButton getBtnZacat() {
        return btnZacat;
    }

    public JLabel getLblPercento() {
        return lblPercento;
    }

}
